#pragma once

struct Node;
struct Statement;
struct ExpressionNode;
struct ExpressionStmt;
struct DeclarationNode;
struct DeclarationStmt;
struct AssignmentStmt;
struct SimpleNode;
struct CallNode;
struct AttrNode;
struct SliceNode;
struct SeqNode;
struct MapNode;
struct StructNode;
struct ArgNode;
struct BinopNode;
struct ComparisonNode;
struct ConversionNode;
struct NotNode;
struct IfNode;
struct ForNode;
struct WhileNode;